# SmokeFree Fastfile

default_platform(:ios)

platform :ios do
  
  desc "Capture App Store screenshots"
  lane :screenshots do
    snapshot
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "App",
      export_method: "app-store"
    )
    upload_to_testflight
  end

  desc "Build and submit to App Store"
  lane :release do
    build_app(
      scheme: "App", 
      export_method: "app-store"
    )
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true
    )
  end

end
